### PR TITLE
Add AlmaLinux 8 support

### PR DESCRIPTION
**Pull request by ezamriy**
Adds vars/AlmaLinux_8.yml required for running on AlmaLinux.

### CODE REVIEW

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest commit:3dad9ffba8f6c9d7380ced55879f6c4d03776b6e]

**Comment by richm** [comment]
[citest pending]

**Review by imgrant — COMMENTED** [review]
This leaves out `vdo` and `kmod-vdo`, which differs from `RedHat_8.yml`, `CentOS_8.yml` and `Rocky_8.yml` — is there a reason? Perhaps it should include them? (AlmaLinux 8 has them)

**Comment by richm** [comment]
closing in favor of https://github.com/linux-system-roles/storage/pull/386

**Pull request closed without merging**
