### PR TITLE
percentage-based volume size (lvm only)

### PR DESCRIPTION
**Pull request by dwlehman**
We probably need to start checking volume sizes to make these tests meaningful.

### CODE REVIEW

**Comment by pcahyna** [comment]
[citest bad]

**Comment by pcahyna** [comment]
should fix #11

**Comment by i386x** [comment]
[citest bad]

**Comment by yontalcar** [comment]
[citest bad]

**Comment by pcahyna** [comment]
should be rebased, new master has fixes for older Ansible (the version that we have in CI)

**Comment by dwlehman** [comment]
Some questions raised by this work:

1. If we want to allow trimming non-percentage-basis sizes to allow, eg: creating two 10GiB LVs in a VG on a 20GiB disk, which is generally not possible due to LVM's metadata taking up some space, should there be a maximum percentage we trim w/o an error? [The size-cap commit should be removed to a separate pull request since it is distinct from the thrust of this one; probably the same for the resize-specific commits.]

2. When doing output validation, we probably cannot expect sizes to match down to the byte. So there will have to be some tolerance. How much is appropriate?

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Comment by nhosoi** [comment]
[citest bad]

**Comment by richm** [comment]
> Some questions raised by this work:
> 
>     1. ~If we want to allow trimming non-percentage-basis sizes to allow, eg: creating two 10GiB LVs in a VG on a 20GiB disk, which is generally not possible due to LVM's metadata taking up some space, should there be a maximum percentage we trim w/o an error? [The size-cap commit should be removed to a separate pull request since it is distinct from the thrust of this one; probably the same for the resize-specific commits.]~ _This has been removed and will appear in another pull request._
> 
>     2. When doing output validation, we probably cannot expect sizes to match down to the byte. So there will have to be some tolerance. How much is appropriate?

I think we will need to do some trial and error to figure out what would be a good tolerance - I would start with -5% to +5%

Also - do the docs need to be updated?

**Comment by richm** [comment]
ping - any updates planned for this PR?  This is planned for rhel 8.5

**Comment by richm** [comment]
> ping - any updates planned for this PR? This is planned for rhel 8.5

ping

**Comment by dwlehman** [comment]
[citest bad]

**Comment by richm** [comment]
> [citest bad]

@dwlehman the rhel-8-y test failure is due to mdadm https://bugzilla.redhat.com/show_bug.cgi?id=1917308 - the rhel-x test failure is due to vdo support on rhel-9

**Comment by richm** [comment]
rhel-x test failure fix - https://github.com/linux-system-roles/storage/pull/215

**Comment by richm** [comment]
[citest bad] - centos-7/ansible-2.9 crashed trying to start a VM - possible flake

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
CI test results look good enough - let's merge this

**Comment by dwlehman** [comment]
Latest force-push just squashed the README.md change into the main commit. I'm okay to merge or we can wait for CI as a precaution.

**Comment by richm** [comment]
> Latest force-push just squashed the README.md change into the main commit. I'm okay to merge or we can wait for CI as a precaution.

Let's go ahead and merge.  Note for the future that the github "Merge pull request" can also do a "Squash and merge" - this will squash all of the commits in the PR into one commit and merge the single commit.

**Pull request merged**
