### PR TITLE
Pass -F to mke2fs for whole disks in RHEL7.

### LINKED ISSUE #122: storage: format entire disk with ext4 fs on RHEL7 will be failed
Hi
I found this issue when I format one entire disk with ext4 fs on RHEL7, I've to add "fs_create_options: '-F' to fix it, but this option fix still not merged.

# playbook
```
[root@storageqe-62 storage]# cat tests/b.yml 
---
- hosts: all
  become: true
  vars:
    mount_location: '/opt/test1'
    volume_group_size: '5g'

  tasks:
    - include_role:
        name: storage

    - include_tasks: get_unused_disk.yml
      vars:
        min_size: "{{ volume_group_size }}"
        max_return: 1

    - name: tests default fs
      block:
        - name: tests default fs
          include_role:
            name: storage
          vars:
            storage_volumes:
              - name: images
                type: disk
                fs_type: 'ext4'
#                fs_create_options: '-F'
                disks: "{{ unused_disks }}" 
                mount_point: /opt/images

```

# execution log
```
TASK [storage : manage the pools and volumes to match the specified state] *******************************************************************************************************************************
task path: /root/test/storage/tasks/main-blivet.yml:104
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1594026521.65-26203-200113320838419 && echo ansible-tmp-1594026521.65-26203-200113320838419="` echo /root/.ansible/tmp/ansible-tmp-1594026521.65-26203-200113320838419 `" ) && sleep 0'
Using module file /root/test/storage/library/blivet.py
<localhost> PUT /root/.ansible/tmp/ansible-local-25540Evjebv/tmpuruiKs TO /root/.ansible/tmp/ansible-tmp-1594026521.65-26203-200113320838419/AnsiballZ_blivet.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1594026521.65-26203-200113320838419/ /root/.ansible/tmp/ansible-tmp-1594026521.65-26203-200113320838419/AnsiballZ_blivet.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1594026521.65-26203-200113320838419/AnsiballZ_blivet.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1594026521.65-26203-200113320838419/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_blivet_payload_UdK0Ld/ansible_blivet_payload.zip/ansible/modules/blivet.py", line 1173, in run_module
  File "/usr/lib/python2.7/site-packages/blivet3/actionlist.py", line 48, in wrapped_func
    return func(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/blivet3/actionlist.py", line 327, in process
    action.execute(callbacks)
  File "/usr/lib/python2.7/site-packages/blivet3/threads.py", line 53, in run_with_lock
    return m(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/blivet3/deviceaction.py", line 637, in execute
    options=self.device.format_args)
  File "/usr/lib/python2.7/site-packages/blivet3/threads.py", line 53, in run_with_lock
    return m(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/blivet3/formats/__init__.py", line 515, in create
    self._create(**kwargs)
  File "/usr/lib/python2.7/site-packages/blivet3/threads.py", line 53, in run_with_lock
    return m(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/blivet3/formats/fs.py", line 409, in _create
    raise FormatCreateError(e, self.device)
fatal: [localhost]: FAILED! => {
    "actions": [], 
    "changed": false, 
    "crypts": [], 
    "invocation": {
        "module_args": {
            "disklabel_type": null, 
            "packages_only": false, 
            "pools": [], 
            "safe_mode": true, 
            "use_partitions": null, 
            "volumes": [
                {
                    "_device": "/dev/sdd", 
                    "_mount_id": "/dev/sdd", 
                    "_raw_device": "/dev/sdd", 
                    "disks": [
                        "sdd"
                    ], 
                    "encryption": false, 
                    "encryption_cipher": null, 
                    "encryption_key_file": null, 
                    "encryption_key_size": null, 
                    "encryption_luks_version": null, 
                    "encryption_passphrase": null, 
                    "fs_create_options": "", 
                    "fs_label": "", 
                    "fs_overwrite_existing": true, 
                    "fs_type": "ext4", 
                    "mount_check": 0, 
                    "mount_device_identifier": "uuid", 
                    "mount_options": "defaults", 
                    "mount_passno": 0, 
                    "mount_point": "/opt/images", 
                    "name": "images", 
                    "raid_chunk_size": null, 
                    "raid_device_count": null, 
                    "raid_level": null, 
                    "raid_metadata_version": null, 
                    "raid_spare_count": null, 
                    "size": 0, 
                    "state": "present", 
                    "type": "disk"
                }
            ]
        }
    }, 
    "leaves": [], 
    "mounts": [], 
    "msg": "Failed to commit changes to disk: (FSError('format failed: 1',), u'/dev/sdd')", 
    "packages": [
        "dosfstools", 
        "xfsprogs", 
        "e2fsprogs", 
        "lvm2"
    ], 
    "pools": [], 
    "volumes": []
}

PLAY RECAP ***********************************************************************************************************************************************************************************************
localhost                  : ok=31   changed=0    unreachable=0    failed=1    skipped=19   rescued=0    ignored=0 
```
# cat /tmp/blivet3.log

```
2020-07-06 05:08:46,224 INFO program/MainThread: Running... mke2fs -t ext4 /dev/sdd
2020-07-06 05:08:46,233 INFO program/MainThread: stdout:
2020-07-06 05:08:46,233 INFO program/MainThread: /dev/sdd is entire device, not just one partition!
2020-07-06 05:08:46,233 INFO program/MainThread: Proceed anyway? (y,n) 
2020-07-06 05:08:46,233 INFO program/MainThread: stderr:
2020-07-06 05:08:46,233 INFO program/MainThread: mke2fs 1.42.9 (28-Dec-2013)
2020-07-06 05:08:46,234 DEBUG program/MainThread: Return code: 1
```

### PR DESCRIPTION
**Pull request by dwlehman**
Fixes #122

### CODE REVIEW

**Comment by yizhanglinux** [comment]
Verified it on RHEL7/RHEL8

**Comment by pcahyna** [comment]
Thank you, this fixes a real problem, but I would prefer checking for distribution/version to happen outside the module, where it is is fairly hidden and makes it more difficult to add support for new distributions. I think it would be better to encapsulate it in the role vars, because platform dependencies are already covered there.
By the way, do you have a method to trigger the problem in the CI? AFAICT the CI passes even with the old version with the bug, which indicates some gap in test coverage.

**Comment by dwlehman** [comment]
You're suggesting something along the lines of a variable `force_mke2fs_whole_disk` that is then passed into the blivet module?

**Comment by dwlehman** [comment]
As far as CI coverage, I think we would have to have five disks to reach a minor of 64 and trigger the prompt.

@pcahyna do you think it's reasonable to pass vars describing behaviors like this into the blivet module, eg: `mkfs_ext2_whole_disk_requires_force=True`, or did you have another method in mind?

**Comment by yizhanglinux** [comment]
This is more related to the majo num, the vda-vdf 's major num is 254, it's neithor **HD_MAJOR**  nor **SCSI_BLK_MAJOR**

And I tried setup iscsi and reproduced this issue
```
[root@ibm-p8-kvm-03-guest-02 e2fsprogs]# lsblk 
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
fd0      2:0    1    4K  0 disk 
sda      8:0    0   10G  0 disk 
sdb      8:16   0   10G  0 disk 
sdc      8:32   0   10G  0 disk 
sr0     11:0    1  364K  0 rom  
vda    253:0    0   10G  0 disk 
└─vda1 253:1    0   10G  0 part /
vdb    253:16   0    1G  0 disk 
vdc    253:32   0    1G  0 disk 
vdd    253:48   0    1G  0 disk 
vde    253:64   0    1G  0 disk 
vdf    253:80   0    1G  0 disk 

[root@ibm-p8-kvm-03-guest-02 e2fsprogs]# uname  -r
3.10.0-1127.el7.x86_64

[root@ibm-p8-kvm-03-guest-02 e2fsprogs]# mkfs.ext4 /dev/sda
mke2fs 1.42.9 (28-Dec-2013)
/dev/sda is entire device, not just one partition!
Proceed anyway? (y,n)

commit 97e9b970769b1afe462f82390cb5876cf037b903
Author: Richard Yao <richard.yao@clusterhq.com>
Date:   Sun Jun 14 14:50:53 2015 -0400

    misc: remove broken whole device check
    
    Modern Linux major/minor numbering on block devices no longer conform to
    the divisible by 64 rule for minor numbering. On my development system,
    the correct number is 16. Consequently, this applies only to every 4th
    drive on a modern system, which is inconsistent. That caused the
    following bug to be filed against Flocker:
    
    https://clusterhq.atlassian.net/browse/FLOC-2041
    
    We could unconditionally pass -F to override this check whenever it
    triggers, but that it would also override the libblkid check that
    determines whether there are existing partitions, logical volumes or
    filesystems on the disk, which seems unwise.
    
    I propose that this check be removed because passing a whole disk to
    mke2fs is a valid use case and given how long this has been broken,
    users are already accustomed to the behavior where -F is not necessary
    to format a whole disk as ext4.
    
    Signed-off-by: Richard Yao <ryao@gentoo.org>
    Signed-off-by: Theodore Ts'o <tytso@mit.edu>
    Reviewed-by: Andreas Dilger <adilger@dilger.ca>

diff --git a/misc/plausible.c b/misc/plausible.c
index 1848a26..97492b9 100644
--- a/misc/plausible.c
+++ b/misc/plausible.c
@@ -18,9 +18,6 @@
 #include "config.h"
 #include <fcntl.h>
 #include <time.h>
-#ifdef HAVE_LINUX_MAJOR_H
-#include <linux/major.h>
-#endif
 #include <sys/types.h>
 #ifdef HAVE_SYS_STAT_H
 #include <sys/stat.h>
@@ -265,35 +262,6 @@ int check_plausibility(const char *device, int flags, int *ret_is_dev)
        if (ret >= 0)
                return ret;
 
-#ifdef HAVE_LINUX_MAJOR_H
-#ifndef MAJOR
-#define MAJOR(dev)     ((dev)>>8)
-#define MINOR(dev)     ((dev) & 0xff)
-#endif
-#ifndef SCSI_BLK_MAJOR
-#ifdef SCSI_DISK0_MAJOR
-#ifdef SCSI_DISK8_MAJOR
-#define SCSI_DISK_MAJOR(M) ((M) == SCSI_DISK0_MAJOR || \
-       ((M) >= SCSI_DISK1_MAJOR && (M) <= SCSI_DISK7_MAJOR) || \
-       ((M) >= SCSI_DISK8_MAJOR && (M) <= SCSI_DISK15_MAJOR))
-#else
-#define SCSI_DISK_MAJOR(M) ((M) == SCSI_DISK0_MAJOR || \
-       ((M) >= SCSI_DISK1_MAJOR && (M) <= SCSI_DISK7_MAJOR))
-#endif /* defined(SCSI_DISK8_MAJOR) */
-#define SCSI_BLK_MAJOR(M) (SCSI_DISK_MAJOR((M)) || (M) == SCSI_CDROM_MAJOR)
-#else
-#define SCSI_BLK_MAJOR(M)  ((M) == SCSI_DISK_MAJOR || (M) == SCSI_CDROM_MAJOR)
-#endif /* defined(SCSI_DISK0_MAJOR) */
-#endif /* defined(SCSI_BLK_MAJOR) */
-       if (((MAJOR(s.st_rdev) == HD_MAJOR &&
-             MINOR(s.st_rdev)%64 == 0) ||
-            (SCSI_BLK_MAJOR(MAJOR(s.st_rdev)) &&                  
-             MINOR(s.st_rdev)%16 == 0))) {
-               printf(_("%s is entire device, not just one partition!\n"),
-                      device);
-               return 0;
-       }
-#endif
        return 1;
 }
```

**Comment by pcahyna** [comment]
@dwlehman I meant something a bit more generic, see https://github.com/pcahyna/storage/tree/el7-ext4-whole-disk

**Comment by dwlehman** [comment]
Closing as obsoleted by #154

**Pull request closed without merging**
