### PR TITLE
Allow specifying only one VDO option

### PR DESCRIPTION
**Pull request by pablomh**
Until now, if one of the two VDO options (compression or deduplication) wasn't desired, it had to be explicitely set to `False`, which shouldn't be needed as per my understanding of the documentation.

### CODE REVIEW

**Comment by vojtechtrefny** [comment]
Can you please share the playbook you are using? I modified our VDO test case to set only `compression: true` and it seems to be working fine:

```
            storage_pools:
              - name: pool1
                disks: "{{ unused_disks }}"
                volumes:
                  - name: volume1
                    compression: true
                    vdo_pool_size: "{{ pool_size }}"
                    size: "{{ volume_size }}"
                    mount_point: "{{ mount_location }}"
```

**Comment by pablomh** [comment]
Hi,

In my case I'm only interested in dedup. My code was this:

```
storage_pools:
  - name: container_data
    disks:
      - vdb
    volumes:
      - name: containers_storage
        deduplication: True
        vdo_pool_size: 50G
        size: 500G
        fs_create_options: '-K'
        mount_point: /var/lib/containers/storage
```

**Comment by vojtechtrefny** [comment]
And this fails with latest storage role from git? I tried with both the git version and the version available in RHEL 9 (`rhel-system-roles-1.20.0-1.el9.noarch`) and the playbook below (I just changed sizes and disk name) works for me:

```
---
- hosts: all
  become: true
  vars:
    storage_safe_mode: false
    storage_use_partitions: true

  tasks:
    - name: Create LVM VDO volume
      include_role:
        name: linux-system-roles.storage
      vars:
        storage_pools:
          - name: container_data
            disks:
              - sdb
            volumes:
              - name: containers_storage
                deduplication: True
                vdo_pool_size: 5G
                size: 50G
                mount_point: /var/lib/containers/storage
                fs_create_options: '-K'
```

```
# sudo lvs -oname,vdo_deduplication,vdo_compression container_data/containers_storage
  LV                 VDODeduplication VDOCompression
  containers_storage          enabled               
```

We made some changes to parameters parsing and defaults in #223, but that's a relatively old change and should be already available everywhere.

**Comment by pablomh** [comment]
I'll close this PR as I'm not able to reproduce it anymore :(

Sorry for having wasted your time!

**Pull request closed without merging**
