### PR TITLE
Add "- name" to tasks/main-blivet.yml ; Add raid 1 5 6 10 to create

### PR DESCRIPTION
**Pull request by FineFan**
"- name" to tasks/main-blivet.yml 
 Add raid 1 5 6 10 to create raid    tests/tests_create_raid_pool_then_remove.yml

### CODE REVIEW

**Comment by yizhanglinux** [comment]
[citest]

**Comment by pcahyna** [comment]
Hi @yizhanglinux, you can not trigger tests by just using the `citest` command if CI does not want to run the tests, you need to provide the commit ID to whitelist it, as documented here: https://github.com/linux-system-roles/test-harness#commands. The reason why the CI refuses to run on every commits automatically is that @FineFan did not accept the invite to the project.

**Comment by richm** [comment]
[citest commit:f297e92e6a9195d7adfdbb0f6346e0d40d78587a]

**Comment by yizhanglinux** [comment]
@FineFan  Pls combine the second and third to one patch.

**Comment by yizhanglinux** [comment]
And the raid6 need 4 disks, but currently provision.fmf only defined 3 disks.

**Comment by FineFan** [comment]
I think I need to close this one , create a new  PR.

**Pull request closed without merging**
