### PR TITLE
Added support for NVME and SCSI HW test setup

### PR DESCRIPTION
**Pull request by japokorn**
EDIT: Following description is no longer accurate. Please see the conversation for details.

This commit serves to cover the gap in testing until CI rework is complete.
CI currently does not support creation of multiple VMs to run the tests
with different hardware settings. To overcome this, provision.fmf will now create
single VM with triple the amount of disks - additional disks will use NVME and SCSI respectively.
find_unused_disk will filter its results by specified interface.
All the tests are run three times in total - each time with different interface.
Runs with NVME/SCSI interfaces are invoked by "tests_run_all_with_interface.yml".

IMPORTANT: When adding a new test file into tests folder, make sure to
include it into list_of_tests.yml. Not doing so will result in incomplete
test coverage. Warning message will also be produced.

### CODE REVIEW

**Comment by richm** [comment]
I think I understand what you want to do - run all of the storage tests with interface default, nvme, and scsi - and I understand why you did it the way you did, since there is no way to import or include a playbook from within a task in a play, and you did not want to have to change every single `tests_*.yml` file - but this is an inelegant way to do it.

Maybe in the future TMT https://docs.fedoraproject.org/en-US/ci/tmt/ has a way to run a matrix of `tests_*.yml` test files by a list of parameters for each test, once we are able to use TMT in CI testing.

The network role also has a similar requirement - to run tests in playbooks that already exist with both `initscripts ` and `nm` - I think they have a script which generates the tests https://github.com/linux-system-roles/network/blob/main/tests/ensure_provider_tests.py - so given a file `tests_default.yml` the script will generate `tests_default_nm.yml` and `tests_default_initscripts.yml` - When a developer creates a new test, they run the script to generate the test for both providers, and commit the generated tests to git.  But I realize that's a lot of work, and not functionally different from having new developers edit `tests/list_of_tests.yml`

@dwlehman @pcahyna @nhosoi @spetrosi wdyt?

**Comment by japokorn** [comment]
@richm I am aware that this approach is not optimal. 

This PR is intended as a temporary solution to fix test coverage until new CI is in place. The change also affects as little of existing code as possible, so it could be easily removed later.

Personally, I do not like the one enormous test file either and the network role approach might be a better way to go.
However, I believe they actually need to run the generating script not only when a new file is added. Each time they change something in the tests, they need to update those generated files. (hm, maybe pre-commit git hook?)

Anyway, I really hope that with the new CI it will be possible to achieve the same thing with simply expanding the inventory with additional VMs.

**Comment by japokorn** [comment]
I have modified how running the additional tests is handled. Instead of one large playbook which imports all the tests twice, a new script was added that automatically generates new playbooks based on discovered `tests_*.yml` files.

Two additional scripts in `/tests/scripts` directory `pre-commit` and `post-commit` are git hooks that ensure that tests are generated and added to the new commit.

However these two scripts have to be manually copied to `<storage_role_repo>/.git/hooks/` and made executable for hook to work.

**Review by richm — APPROVED** [review]
lgtm

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
@japokorn please rebase

**Comment by japokorn** [comment]
rebased

**Comment by richm** [comment]
@japokorn there are some more changes you'll need to do which depend on the commits I made to your branch:

you will need to regenerate all of the generated tests/ files to resolve the ansible-lint issue

you will need to make the following changes:
```patch
diff --git a/.sanity-ansible-ignore-2.10.txt b/.sanity-ansible-ignore-2.10.txt
index 1f7c913..01e1772 100644
--- a/.sanity-ansible-ignore-2.10.txt
+++ b/.sanity-ansible-ignore-2.10.txt
@@ -19,3 +19,8 @@ plugins/modules/lvm_gensym.py validate-modules:module-invalid-version-added
 plugins/modules/resolve_blockdev.py validate-modules:missing-gplv3-license
 plugins/modules/resolve_blockdev.py validate-modules:module-invalid-version-added
 plugins/module_utils/storage_lsr/size.py pep8!skip
+tests/storage/scripts/generate_tests.py shebang
+tests/storage/scripts/generate_tests.py metaclass-boilerplate!skip
+tests/storage/scripts/generate_tests.py future-import-boilerplate!skip
+tests/storage/scripts/pre-commit shebang
+tests/storage/scripts/post-commit shebang
diff --git a/.sanity-ansible-ignore-2.9.txt b/.sanity-ansible-ignore-2.9.txt
index 93eaeaf..cfd55b7 100644
--- a/.sanity-ansible-ignore-2.9.txt
+++ b/.sanity-ansible-ignore-2.9.txt
@@ -12,3 +12,8 @@ plugins/modules/find_unused_disk.py validate-modules:missing-gplv3-license
 plugins/modules/lvm_gensym.py validate-modules:missing-gplv3-license
 plugins/modules/resolve_blockdev.py validate-modules:missing-gplv3-license
 plugins/module_utils/storage_lsr/size.py pep8!skip
+tests/storage/scripts/generate_tests.py shebang
+tests/storage/scripts/generate_tests.py metaclass-boilerplate!skip
+tests/storage/scripts/generate_tests.py future-import-boilerplate!skip
+tests/storage/scripts/pre-commit shebang
+tests/storage/scripts/post-commit shebang
```
then the tox tests should all pass

**Review by richm — APPROVED** [review]
lgtm

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Pull request merged**
