### PR TITLE
fix most ansible-test issues, suppress the rest

### PR DESCRIPTION
**Pull request by richm**
This also enables flake8 testing for python code after fixing
or suppressing those issues.

### CODE REVIEW

**Comment by richm** [comment]
@dwlehman this is an alternative to https://github.com/linux-system-roles/storage/pull/204 - does not have the `black` formatting changes, but addresses most of the issues - also enables `flake8` testing for storage code

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Comment by nhosoi** [comment]
Can we have  .sanity-ansible-ignore-2.10.txt, too?
Otherwise, lgtm.

**Comment by richm** [comment]
> Can we have .sanity-ansible-ignore-2.10.txt, too?
> Otherwise, lgtm.

Added.  I also fixed some new issues introduced by 2.10 checks.

**Pull request merged**
