### PR TITLE
add setup snapshot to install packages into snapshot

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by richm** [comment]
The goal here is that we can create a snapshot of the VM image pre-loaded with packages that take a long time to install like kmod-kvdo, then use that snapshot for subsequent tests.
The code that creates and initializes the snapshot is here: https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/test_scripts/runqemu.py#L546-L597

**Review by nhosoi — APPROVED** [review]
lgtm

A bit confused that these files are not related to the "snapshot"; just added because they were missing?
tests/tests_create_lvm_cache_then_remove_nvme_generated.yml
tests/tests_create_lvm_cache_then_remove_scsi_generated.yml
tests/tests_fatals_cache_volume_nvme_generated.yml
tests/tests_fatals_cache_volume_scsi_generated.yml

**Comment by richm** [comment]
> lgtm
> 
> A bit confused that these files are not related to the "snapshot"; just added because they were missing? 

yes - the `nvme_generated` and `scsi_generated` are supposed to be generated by the developer upon commit - I have a git post-commit hook that generates these so I don't forget . . .

tests/tests_create_lvm_cache_then_remove_nvme_generated.yml tests/tests_create_lvm_cache_then_remove_scsi_generated.yml tests/tests_fatals_cache_volume_nvme_generated.yml tests/tests_fatals_cache_volume_scsi_generated.yml

**Review by vojtechtrefny — APPROVED** [review]

**Comment by vojtechtrefny** [comment]
> > lgtm
> > A bit confused that these files are not related to the "snapshot"; just added because they were missing?
> 
> yes - the `nvme_generated` and `scsi_generated` are supposed to be generated by the developer upon commit - I have a git post-commit hook that generates these so I don't forget . . .

My bad, that should have been part of #235. I have added a short paragraph about the generated tests to README-devel (#261) so I should remember it next time.

**Review by spetrosi — APPROVED** [review]
lgtm

**Comment by richm** [comment]
[citest]

**Pull request merged**
