### PR TITLE
Do not merge CI: Debug RHEL-9

### PR DESCRIPTION
**Pull request by jharuda**

### CODE REVIEW

**Comment by jharuda** [comment]
Looks like there is an error in ansible-2.9 for RHEL-9. 
@dwlehman   @richm 

David: Do you have an idea what can be wrong in "Set version specific variables"?

TASK [linux-system-roles.storage : Set version specific variables] *************
task path: /tmp/tmp80iio33h/tasks/main.yml:2
fatal: [/cache/rhel-x.qcow2]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'first_found'. Error was a <class 'ansible.errors.AnsibleLookupError'>, original message: No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found"}

**Comment by richm** [comment]
> Looks like there is an error in ansible-2.9 for RHEL-9.
> @dwlehman @richm
> 
> David: Do you have an idea what can be wrong in "Set version specific variables"?
> 
> TASK [linux-system-roles.storage : Set version specific variables] *************
> task path: /tmp/tmp80iio33h/tasks/main.yml:2
> fatal: [/cache/rhel-x.qcow2]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'first_found'. Error was a <class 'ansible.errors.AnsibleLookupError'>, original message: No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found"}

There is no `vars/RedHat_9.yml`

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Comment by nhosoi** [comment]
All the CI tests passed!
Can we have resume the deleted items in meta/main.yml and remove "Do not merge" from title?

**Pull request closed without merging**
