### PR TITLE
Blivet backend WIP

### PR DESCRIPTION
**Pull request by dwlehman**
This is a rough WIP version. I want to get the CI running on it while I clean some things up.

### CODE REVIEW

**Comment by pcahyna** [comment]
don't worry too much about the -staging failures and errors, that infrastructure is flaky.

**Comment by pcahyna** [comment]
@dwlehman do you have any updates on this or is it ready for review?

**Comment by dwlehman** [comment]
[citest all]

**Comment by dwlehman** [comment]
[citest all]

**Comment by dwlehman** [comment]
[citest bad]

**Comment by dwlehman** [comment]
I would like to improve the structure of the code in `library/blivet.py` (to add some encapsulation around various volume types, but I think as of now the functionality is mostly in place for v1. One exception is partitioning which, although straightforward, will probably take a few hours to get right. It's worth noting that the tests involving partitions appear to not effectively test that partitions are actually used, which we'll want to fix.

Having said that, I think we need to focus on the functionality and the interfaces, and I can improve the internals later.

**Comment by dwlehman** [comment]
As of now the support is there for a single partition that spans the whole disk, either as a volume or as a backing device for a pool. The former case is verified during testing, while the latter is not.

**Pull request merged**
