### PR TITLE
Fix issues found by linters - enable all tests on all repos - remove suppressions

### PR DESCRIPTION
**Pull request by nhosoi**
- Cleaning up yamllint line-length errors
- Cleaning up ansible-lint errors

### CODE REVIEW

**Comment by nhosoi** [comment]
Note: there was no conflict with https://github.com/linux-system-roles/storage/pull/204 or https://github.com/linux-system-roles/storage/pull/205. I had no problem to rebase with either of them.

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Review by dwlehman — APPROVED** [review]
Looks fine to me.

**Pull request merged**
