### PR TITLE
skip vdo test if kernel module is not loadable

### PR DESCRIPTION
**Pull request by richm**
The vdo kernel module is an "out of tree" module which means that it
may not be available if the vdo module version does not match the
current kernel version.  In that case, skip the vdo test so that we
don't get a false positive test result.

### CODE REVIEW

**Comment by richm** [comment]
@vojtechtrefny fyi

**Review by dwlehman — APPROVED** [review]
I think the four added files in tests/ should be dropped, but otherwise it looks good to me.

**Review by japokorn — APPROVED** [review]
Looks good to me.

Generated vdo test files for nvme and iscsi are currently missing in the main branch and I believe they should be added there.

**Comment by dwlehman** [comment]
> Generated vdo test files for nvme and iscsi are currently missing in the main branch and I believe they should be added there.

Ah, ok. Makes sense to me.

**Comment by richm** [comment]
[citest bad] - some weird flakes on rhel7 and rhel9

**Comment by richm** [comment]
@dwlehman @japokorn yay - rhel-x tests passed - ready to merge?

**Pull request merged**
