### PR TITLE
WIP: initial integration tests

### PR DESCRIPTION
**Pull request by dwlehman**
Playing around to see how to get scratch disks in the vm, etc.

### CODE REVIEW

**Comment by tyll** [comment]
[citest bad]

**Comment by tyll** [comment]
[citest pending]

**Comment by tyll** [comment]
[citest bad]

**Comment by pcahyna** [comment]
@tyll @timflannagan1 As I understood this PR is superseded by #17 so we should probably not let the CI re-test it.

**Comment by timflannagan1** [comment]
Closing this as #17 supersedes this PR, and was merged.

**Pull request closed without merging**
